FROM python:3.9-slim

WORKDIR /app

# התקנת תלויות מערכת
RUN apt-get update && apt-get install -y libpq-dev gcc

# העתקת ה-requirements (שים לב ששינינו את השם)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# חשיפת הפורט של FastAPI
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]